### ISSUE TITLE
Minor Bug with Variable generation.

### ISSUE THREAD

**Issue by ahenry3068** [stefan-b-jakobsson/basload#10]
The following line of code was a typo on my part and I think it should have stopped with a Syntax Error

PRINT "F12"$;

Instead the stray $ was turned into a numerical variable by BASLOAD.   The resulting Output program printed a Zero complete with leading space.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by stefan-b-jakobsson** [comment]
This issue was intended for the basload-rom project.
